---
title: "Tidycensus data plot"
author: "Elzbieta Jodlowska-Siewert"
format: 
  html:
    embed-resources: true
editor: visual
---

```{r include=FALSE}
library(osmdata)
library(ggmap)
library(sf)
library(ggthemes)
library(scales)
library(tidycensus)
library(htmltools, quietly = TRUE)
library(viridis, quietly = TRUE)
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)


## Load the API key
tidycensus_key <- Sys.getenv("TIDYCENSUS_API_KEY")
census_api_key(tidycensus_key)

mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)
mn_base.map <- get_map(
  location = hennepin.box,
  source   = "stamen",
  maptype  = "terrain",
  crop = TRUE
)

hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 12,
                                hjust = 0.5),
    legend.text  = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.position = "right"
  )

mn_hours.df <- get_acs(
  geography = "tract",
  variables = "B23020_001E", 
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE,
  cb        = FALSE
)

mn_hours_plotly.df <- mn_hours.df %>%
  mutate(
    tract = str_split(NAME, ",") %>%
      map_chr(1) %>%
      str_remove("Census Tract "),
    text_label = str_c(
      "Tract: ",
      tract,
      "\nMean hours worked: ",
      estimate, " hours"
    )
  )

coord_ggmap <- st_crs(hennepin_base.gg)
coord_sf    <- st_crs(mn_hours_plotly.df)

mn_hours.ggmap <- hennepin_base.gg +  
  geom_sf(data = mn_hours_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1,
          inherit.aes = FALSE) + 
  labs(title = "Hennepin County 2020 ACS Mean Hours Worked (per week)") + 
  scale_fill_viridis_c("Mean hours worked") +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 12,
                                hjust = 0.5),
    legend.text  = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.position = "top"
  )

mn_hours.ggplotly<-ggplotly(mn_hours.ggmap, tooltip = "text", height  = 600,
         width   = 800) %>%
  style(hoveron = "fills")
```

```{r}
mn_hours.ggplotly
```